export const infoproducts =[
       {identifier:0, title:'Demolisher', desc:'You will only hear their singing arrows when is too late  ',
       extra:'Equipped with the deadliest set of arrows ever created', price:20},
       {identifier:1, title:'Bomber', desc:'They don`t just disappear into the darkness, they ARE darkness  ',
       extra:'Their natural infra-red vision makes them the best night fighters', price:40},
       {identifier:2, title:'Tinkerer', desc:'They are not healers and doctors, as their name imply  ',
       extra:'They bring balance back to nature, with your blood', price:35},
       {identifier:3, title:'Singer', desc:'You will only hear their singing arrows when is too late  ',
       extra:'Equipped with the deadliest set of arrows ever created', price:10},
       {identifier:4, title:'Shadower', desc:'They don`t just disappear into the darkness, they ARE darkness  ',
       extra:'Their natural infra-red vision makes them the best night fighters', price:15},
       {identifier:5, title:'Restorer', desc:'They are not healers and doctors, as their name imply  ',
       extra:'They bring balance back to nature, with your blood', price:30},
       {identifier:6, title:'Thunderstorm', desc:'You will only hear their singing arrows when is too late  ',
       extra:'Equipped with the deadliest set of arrows ever created', price:1500},
       {identifier:7, title:'Nihilist', desc:'They don`t just disappear into the darkness, they ARE darkness  ',
       extra:'Their natural infra-red vision makes them the best night fighters', price:2000},
       {identifier:8, title:'Sons of Uncle Bob', desc:'They are not healers and doctors, as their name imply  ',
       extra:'They bring balance back to nature, with your blood', price:800},
];
