export const infoproducts =[
       {identifier:0, title:'Demolisher', desc:'Sometimes the best attack... is attack  ',
       extra:'Not the brightest, but definitely the toughest', price:20},
       {identifier:1, title:'Bomber', desc:'Give some chemistry skills to the naughty boys  ',
       extra:'BOOOOOOOM!!!', price:40},
       {identifier:2, title:'Tinkerer', desc:'Is not all about rocks and caverns  ',
       extra:'Some dwarves take metal skills to the next level', price:35},
       {identifier:3, title:'Singer', desc:'You will only hear their singing arrows when is too late  ',
       extra:'Equipped with the deadliest set of arrows ever created', price:10},
       {identifier:4, title:'Shadower', desc:'They don`t just disappear into the darkness, they ARE darkness  ',
       extra:'Their natural infra-red vision makes them the best night fighters', price:15},
       {identifier:5, title:'Restorer', desc:'They are not healers and doctors, as their name imply  ',
       extra:'They bring balance back to nature, with your blood', price:30},
       {identifier:6, title:'Thunderstorm', desc:'Mother Nature has never been so pissed  ',
       extra:'When metal armor is your worst protection', price:1500},
       {identifier:7, title:'Nihilist', desc:'What comes after total destruction?  ',
       extra:'They', price:2000},
       {identifier:8, title:'Sons of Uncle Bob', desc:'Bob has more than he can remember  ',
       extra:'Small, dumb and deadly... like Gremlins on steroids', price:800},
];
